version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - ".github/**/*"
    schedule:
      interval: "monthly"
    labels:
      - "actions-update"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
  - package-ecosystem: "github-actions"
    directories:
      - ".github/**/*"
    target-branch: "release/0.2.x"
    schedule:
      interval: "monthly"
    labels:
      - "actions-update"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "release/0.2.x"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot*"
        versions:
          - ">=4.0.0"
      - dependency-name: "org.springframework.cloud:*"
        versions:
          - ">=2025.1.0"
      - dependency-name: "io.github.rabobank:shadow-tool"
        versions:
          - ">=1.8.0"
